# Generated by Django 2.2 on 2020-03-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200330_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='title_groups',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_posts',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='group_posts',
        ),
    ]
