# Generated by Django 2.2 on 2020-03-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200330_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title_groups',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author_posts',
            new_name='author',
        ),
    ]
